version: 2
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      docker:
        - image: circleci/openjdk:11.0.3-jdk-stretch
      steps:
        - checkout
        - run
            command: ./gradlew test
workflows:
  version: 2
  workflow:
    jobs:
      - build
