version: 2
jobs:
  test:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: ./gradlew test
      - store_test_results:
          path: core/build/test-results/test
      - store_artifacts:
          path: core/build/reports/tests
      - store_test_results:
          path: datafeeder/build/test-results/test
      - store_artifacts:
          path: datafeeder/build/reports/tests
      - store_test_results:
          path: flights/build/test-results/test
      - store_artifacts:
          path: flights/build/reports/tests
      - store_test_results:
          path: flight-processor/build/test-results/test
      - store_artifacts:
          path: flight-processor/build/reports/tests
      - store_test_results:
          path: flights-web-viewer/build/test-results/test
      - store_artifacts:
          path: flights-web-viewer/build/reports/tests
workflows:
  version: 2
  workflow:
    jobs:
      - test
